import {
  blobPathBuilders,
  keyBuilders,
  type DataLayerService,
  type WorkflowDocument,
} from '../../../../src/index.js';

const demoTimestamp = '2026-03-12T14:00:00.000Z';
const recentTimestamp = '2026-03-12T15:25:00.000Z';
const operatorUserObjectId = '7d7494c2-7dc4-4d7e-95ef-6fdc8db3db5a';

let seedPromise: Promise<DataLayerService> | undefined;

export const demoContext = {
  mspTenantId: 'msp_demo',
  operatorUserObjectId,
  defaultInputProfileId: 'profile_default',
  highlightedClientTenantId: 'tenant_northwind',
};

export async function ensureDemoData(
  service: DataLayerService,
  currentRuntimeMode: 'memory' | 'azure',
): Promise<DataLayerService> {
  const shouldSeedAzure = process.env.AOIFMSP_ENABLE_DEMO_SEED === 'true';

  if (currentRuntimeMode === 'azure' && !shouldSeedAzure) {
    return service;
  }

  if (!seedPromise) {
    seedPromise = seedData(service).catch((error) => {
      seedPromise = undefined;
      throw error;
    });
  }

  return seedPromise;
}

async function seedData(service: DataLayerService): Promise<DataLayerService> {
  const existingTenant = await service.tables.mspTenants.getByKey(demoContext.mspTenantId);

  if (existingTenant) {
    return service;
  }

  const northwindClientId = 'tenant_northwind';
  const wingtipClientId = 'tenant_wingtip';
  const ticketTriageWorkflowId = 'wf_demo_ticket_triage';
  const onboardingWorkflowId = 'wf_demo_user_onboarding';
  const driftWorkflowId = 'wf_demo_standards_drift';

  await Promise.all([
    service.tables.mspTenants.upsert({
      ...keyBuilders.entity.mspTenant(demoContext.mspTenantId),
      id: demoContext.mspTenantId,
      m365TenantId: '7f1f3dc5-d8c8-442c-8944-60489c95f2a5',
      displayName: 'Contoso MSP',
      primaryDomain: 'contosomsp.com',
      status: 'active',
      billingState: 'paid',
      defaultRegion: 'eastus2',
      settingsBlobPath: blobPathBuilders.tenantSettings(demoContext.mspTenantId),
      preferredFoundrySetupMode: 'basic',
      gdapRelationshipState: 'active',
      defaultAdminAuthMode: 'gdap-obo',
      schemaVersion: 1,
      createdAt: demoTimestamp,
      createdBy: 'system:seed',
      updatedAt: recentTimestamp,
      updatedBy: 'system:seed',
    }),
    service.tables.mspUsers.upsert({
      ...keyBuilders.entity.mspUser(demoContext.mspTenantId, operatorUserObjectId),
      id: 'operator_reed',
      mspTenantId: demoContext.mspTenantId,
      userObjectId: operatorUserObjectId,
      userPrincipalName: 'reed@contosomsp.com',
      displayName: 'Reed Harper',
      rolesCsv: 'GlobalAdmin,TechnicianLead,AutomationBuilder',
      status: 'active',
      lastLoginAt: recentTimestamp,
      createdAt: demoTimestamp,
      createdBy: 'system:seed',
      updatedAt: recentTimestamp,
      updatedBy: 'system:seed',
    }),
    service.tables.userPreferences.upsert({
      ...keyBuilders.entity.userPreferences(demoContext.mspTenantId, operatorUserObjectId),
      mspTenantId: demoContext.mspTenantId,
      userObjectId: operatorUserObjectId,
      themeMode: 'light',
      densityMode: 'comfortable',
      preferredStartSurface: 'technician-workspace',
      layoutPreferencesJson: JSON.stringify({
        panels: {
          technician: { width: 780 },
          inspector: { collapsed: false },
        },
      }),
      commandPaletteHistoryJson: JSON.stringify(['Open Ticket Workspace', 'Run Guided Action']),
      onboardingProgressJson: JSON.stringify({
        workflowDesigner: 'introduced',
        tenantAdministration: 'active',
      }),
      featureExposureMode: 'guided',
      updatedAt: recentTimestamp,
    }),
    service.tables.userInputProfiles.upsert({
      ...keyBuilders.entity.userInputProfile(
        demoContext.mspTenantId,
        operatorUserObjectId,
        demoContext.defaultInputProfileId,
      ),
      mspTenantId: demoContext.mspTenantId,
      userObjectId: operatorUserObjectId,
      profileId: demoContext.defaultInputProfileId,
      displayName: 'Technician Default',
      surfaceScope: 'global',
      isDefault: true,
      bindingMapJson: JSON.stringify({
        actions: {
          'open-command-palette': ['Ctrl+K'],
          'launch-guided-action': ['Space'],
          'inspect-ticket-context': ['Tab'],
          'open-workflow-designer': ['W'],
        },
      }),
      version: 1,
      updatedAt: recentTimestamp,
    }),
    service.tables.clientTenants.upsert({
      ...keyBuilders.entity.clientTenant(demoContext.mspTenantId, northwindClientId),
      id: northwindClientId,
      mspTenantId: demoContext.mspTenantId,
      clientTenantId: northwindClientId,
      clientM365TenantId: '8feef8ca-e5b0-4fec-ae8d-1a1533c9e56a',
      displayName: 'Northwind Dental',
      primaryDomain: 'northwinddental.com',
      status: 'active',
      onboardingState: 'complete',
      graphConnectionId: 'conn_graph_northwind',
      defaultUsageLocation: 'US',
      notesBlobPath: blobPathBuilders.clientNotes(demoContext.mspTenantId, northwindClientId),
      createdAt: demoTimestamp,
      createdBy: 'system:seed',
      updatedAt: recentTimestamp,
      updatedBy: 'system:seed',
    }),
    service.tables.clientTenants.upsert({
      ...keyBuilders.entity.clientTenant(demoContext.mspTenantId, wingtipClientId),
      id: wingtipClientId,
      mspTenantId: demoContext.mspTenantId,
      clientTenantId: wingtipClientId,
      clientM365TenantId: '21ff58dc-b112-48aa-ae16-c0a33f39a875',
      displayName: 'Wingtip Health',
      primaryDomain: 'wingtiphealth.com',
      status: 'active',
      onboardingState: 'standards-review',
      graphConnectionId: 'conn_graph_wingtip',
      defaultUsageLocation: 'US',
      notesBlobPath: blobPathBuilders.clientNotes(demoContext.mspTenantId, wingtipClientId),
      createdAt: demoTimestamp,
      createdBy: 'system:seed',
      updatedAt: recentTimestamp,
      updatedBy: 'system:seed',
    }),
    service.tables.tenantManagementProfiles.upsert({
      ...keyBuilders.entity.tenantManagementProfile(demoContext.mspTenantId, northwindClientId),
      id: `mgmt_${northwindClientId}`,
      mspTenantId: demoContext.mspTenantId,
      clientTenantId: northwindClientId,
      gdapRelationshipState: 'active',
      gdapRolesJson: JSON.stringify(['User Administrator', 'Groups Administrator', 'Helpdesk Administrator']),
      gdapExpiresAt: '2027-01-18T00:00:00.000Z',
      defaultAdminAuthMode: 'gdap-obo',
      oboServiceAccountRef: 'svc_gdap_ops',
      platformAppRegistrationId: 'appreg_platform_northwind',
      platformPermissionScopeJson: JSON.stringify(['Directory.Read.All', 'offline_access']),
      managementCapabilitiesJson: JSON.stringify(['user-lifecycle', 'licenses', 'standards', 'alerts']),
      lastValidatedAt: recentTimestamp,
      createdAt: demoTimestamp,
      createdBy: 'system:seed',
      updatedAt: recentTimestamp,
      updatedBy: 'system:seed',
    }),
    service.tables.tenantManagementProfiles.upsert({
      ...keyBuilders.entity.tenantManagementProfile(demoContext.mspTenantId, wingtipClientId),
      id: `mgmt_${wingtipClientId}`,
      mspTenantId: demoContext.mspTenantId,
      clientTenantId: wingtipClientId,
      gdapRelationshipState: 'active',
      gdapRolesJson: JSON.stringify(['User Administrator', 'License Administrator']),
      gdapExpiresAt: '2026-11-03T00:00:00.000Z',
      defaultAdminAuthMode: 'gdap-obo',
      oboServiceAccountRef: 'svc_gdap_ops',
      platformAppRegistrationId: 'appreg_platform_wingtip',
      platformPermissionScopeJson: JSON.stringify(['Directory.Read.All', 'offline_access']),
      managementCapabilitiesJson: JSON.stringify(['user-lifecycle', 'licenses', 'alerts']),
      lastValidatedAt: recentTimestamp,
      createdAt: demoTimestamp,
      createdBy: 'system:seed',
      updatedAt: recentTimestamp,
      updatedBy: 'system:seed',
    }),
    service.tables.managedUsers.upsert({
      ...keyBuilders.entity.managedUser(demoContext.mspTenantId, northwindClientId, 'user_anna_morgan'),
      id: 'user_anna_morgan',
      mspTenantId: demoContext.mspTenantId,
      clientTenantId: northwindClientId,
      managedUserId: 'user_anna_morgan',
      entraObjectId: 'c3983c0e-4dfb-42d3-a603-5dd3d7c43cf9',
      userPrincipalName: 'anna.morgan@northwinddental.com',
      displayName: 'Anna Morgan',
      givenName: 'Anna',
      surname: 'Morgan',
      mail: 'anna.morgan@northwinddental.com',
      accountEnabled: true,
      usageLocation: 'US',
      userType: 'Member',
      licenseSummaryJson: JSON.stringify(['Microsoft 365 Business Premium']),
      roleSummaryJson: JSON.stringify(['User']),
      groupSummaryJson: JSON.stringify(['Front Desk']),
      syncSource: 'graph',
      lastGraphSyncAt: recentTimestamp,
      lastManagedAt: recentTimestamp,
      status: 'active',
    }),
    service.tables.managedUsers.upsert({
      ...keyBuilders.entity.managedUser(demoContext.mspTenantId, northwindClientId, 'user_danielle_rivera'),
      id: 'user_danielle_rivera',
      mspTenantId: demoContext.mspTenantId,
      clientTenantId: northwindClientId,
      managedUserId: 'user_danielle_rivera',
      entraObjectId: '0a499110-6b66-46f5-a14d-dd3e8f475ccb',
      userPrincipalName: 'danielle.rivera@northwinddental.com',
      displayName: 'Danielle Rivera',
      givenName: 'Danielle',
      surname: 'Rivera',
      mail: 'danielle.rivera@northwinddental.com',
      accountEnabled: true,
      usageLocation: 'US',
      userType: 'Member',
      licenseSummaryJson: JSON.stringify(['Microsoft Teams Essentials']),
      roleSummaryJson: JSON.stringify(['Billing Contact']),
      groupSummaryJson: JSON.stringify(['Clinic Managers']),
      syncSource: 'graph',
      lastGraphSyncAt: recentTimestamp,
      lastManagedAt: recentTimestamp,
      status: 'active',
    }),
    service.tables.managedUsers.upsert({
      ...keyBuilders.entity.managedUser(demoContext.mspTenantId, wingtipClientId, 'user_mason_shaw'),
      id: 'user_mason_shaw',
      mspTenantId: demoContext.mspTenantId,
      clientTenantId: wingtipClientId,
      managedUserId: 'user_mason_shaw',
      entraObjectId: '3219b72c-a0e1-48fa-86ee-b16f5a5a5e8c',
      userPrincipalName: 'mason.shaw@wingtiphealth.com',
      displayName: 'Mason Shaw',
      givenName: 'Mason',
      surname: 'Shaw',
      mail: 'mason.shaw@wingtiphealth.com',
      accountEnabled: true,
      usageLocation: 'US',
      userType: 'Member',
      licenseSummaryJson: JSON.stringify(['Microsoft 365 E3']),
      roleSummaryJson: JSON.stringify(['Compliance Reader']),
      groupSummaryJson: JSON.stringify(['Clinical Operations']),
      syncSource: 'graph',
      lastGraphSyncAt: recentTimestamp,
      lastManagedAt: recentTimestamp,
      status: 'active',
    }),
    service.tables.devices.upsert({
      ...keyBuilders.entity.device(demoContext.mspTenantId, northwindClientId, 'device_frontdesk_pc'),
      id: 'device_frontdesk_pc',
      mspTenantId: demoContext.mspTenantId,
      clientTenantId: northwindClientId,
      deviceId: 'device_frontdesk_pc',
      sourceSystem: 'NinjaOne',
      sourceDeviceId: 'rmm-1048',
      displayName: 'Front Desk PC',
      deviceType: 'desktop',
      platform: 'Windows 11',
      status: 'attention',
      lastSeenAt: '2026-03-12T15:21:00.000Z',
      primaryUserId: 'user_anna_morgan',
      ticketCount: 2,
      alertCount: 1,
      summary: 'Shared intake workstation with intermittent print spooler failures.',
      lastSourceUpdatedAt: recentTimestamp,
      lastSyncedAt: recentTimestamp,
      sourceUrl: 'https://example.invalid/rmm/device/frontdesk-pc',
    }),
    service.tables.devices.upsert({
      ...keyBuilders.entity.device(demoContext.mspTenantId, wingtipClientId, 'device_lab_surface'),
      id: 'device_lab_surface',
      mspTenantId: demoContext.mspTenantId,
      clientTenantId: wingtipClientId,
      deviceId: 'device_lab_surface',
      sourceSystem: 'NinjaOne',
      sourceDeviceId: 'rmm-2024',
      displayName: 'Lab Surface 7',
      deviceType: 'laptop',
      platform: 'Windows 11',
      status: 'healthy',
      lastSeenAt: '2026-03-12T15:19:00.000Z',
      primaryUserId: 'user_mason_shaw',
      ticketCount: 1,
      alertCount: 0,
      summary: 'Clinical operations laptop with current baseline applied.',
      lastSourceUpdatedAt: recentTimestamp,
      lastSyncedAt: recentTimestamp,
      sourceUrl: 'https://example.invalid/rmm/device/lab-surface',
    }),
    service.tables.documentationRecords.upsert({
      ...keyBuilders.entity.documentationRecord(demoContext.mspTenantId, northwindClientId, 'doc_printer_runbook'),
      id: 'doc_printer_runbook',
      mspTenantId: demoContext.mspTenantId,
      clientTenantId: northwindClientId,
      documentationRecordId: 'doc_printer_runbook',
      sourceSystem: 'Hudu',
      sourceRecordId: 'hudu-334',
      displayName: 'Reception Printer Runbook',
      category: 'Runbook',
      relatedUserId: 'user_anna_morgan',
      relatedDeviceId: 'device_frontdesk_pc',
      relatedTicketId: 'ticket_4512',
      summary: 'Restart spooler, verify shared queue mapping, and confirm paper tray sensor state.',
      lastSourceUpdatedAt: recentTimestamp,
      lastSyncedAt: recentTimestamp,
      sourceUrl: 'https://example.invalid/docs/reception-printer-runbook',
    }),
    service.tables.documentationRecords.upsert({
      ...keyBuilders.entity.documentationRecord(demoContext.mspTenantId, wingtipClientId, 'doc_new_hire_checklist'),
      id: 'doc_new_hire_checklist',
      mspTenantId: demoContext.mspTenantId,
      clientTenantId: wingtipClientId,
      documentationRecordId: 'doc_new_hire_checklist',
      sourceSystem: 'Hudu',
      sourceRecordId: 'hudu-812',
      displayName: 'Clinical New Hire Checklist',
      category: 'Checklist',
      summary: 'Identity, device allocation, Teams policy, and baseline standards reminders.',
      lastSourceUpdatedAt: recentTimestamp,
      lastSyncedAt: recentTimestamp,
      sourceUrl: 'https://example.invalid/docs/new-hire-checklist',
    }),
    service.tables.tickets.upsert({
      ...keyBuilders.entity.ticket(demoContext.mspTenantId, 'ticket_4512'),
      id: 'ticket_4512',
      mspTenantId: demoContext.mspTenantId,
      ticketId: 'ticket_4512',
      sourceSystem: 'HaloPSA',
      sourceTicketId: '4512',
      boardOrQueue: 'Support',
      status: 'triage',
      priority: 'high',
      displayName: 'Printer outage for main reception',
      clientTenantId: northwindClientId,
      relatedUserId: 'user_anna_morgan',
      relatedDeviceId: 'device_frontdesk_pc',
      assignedTechnicianId: operatorUserObjectId,
      summary: 'Reception cannot print intake forms after this morning’s workstation reboot.',
      lastSourceUpdatedAt: recentTimestamp,
      lastSyncedAt: recentTimestamp,
      sourceUrl: 'https://example.invalid/psa/tickets/4512',
    }),
    service.tables.tickets.upsert({
      ...keyBuilders.entity.ticket(demoContext.mspTenantId, 'ticket_4519'),
      id: 'ticket_4519',
      mspTenantId: demoContext.mspTenantId,
      ticketId: 'ticket_4519',
      sourceSystem: 'HaloPSA',
      sourceTicketId: '4519',
      boardOrQueue: 'Identity',
      status: 'ready',
      priority: 'medium',
      displayName: 'Prepare onboarding for new hygienist',
      clientTenantId: wingtipClientId,
      assignedTechnicianId: operatorUserObjectId,
      summary: 'New starter begins Monday and needs identity, licensing, Teams access, and device prep.',
      lastSourceUpdatedAt: recentTimestamp,
      lastSyncedAt: recentTimestamp,
      sourceUrl: 'https://example.invalid/psa/tickets/4519',
    }),
    service.tables.tickets.upsert({
      ...keyBuilders.entity.ticket(demoContext.mspTenantId, 'ticket_4498'),
      id: 'ticket_4498',
      mspTenantId: demoContext.mspTenantId,
      ticketId: 'ticket_4498',
      sourceSystem: 'HaloPSA',
      sourceTicketId: '4498',
      boardOrQueue: 'Standards',
      status: 'waiting',
      priority: 'medium',
      displayName: 'Review MFA standards drift exceptions',
      clientTenantId: northwindClientId,
      assignedTechnicianId: operatorUserObjectId,
      summary: 'Baseline detected new exception accounts and needs technician review before auto-remediation.',
      lastSourceUpdatedAt: recentTimestamp,
      lastSyncedAt: recentTimestamp,
      sourceUrl: 'https://example.invalid/psa/tickets/4498',
    }),
    service.tables.managementAlerts.upsert({
      ...keyBuilders.entity.managementAlert(demoContext.mspTenantId, 'alert_print_spooler', '2026-03-12T15:18:00.000Z'),
      id: 'alert_print_spooler',
      mspTenantId: demoContext.mspTenantId,
      clientTenantId: northwindClientId,
      alertType: 'device-health',
      severity: 'medium',
      sourceType: 'device',
      sourceId: 'device_frontdesk_pc',
      title: 'Print spooler failures detected',
      summary: 'Front Desk PC has restarted the print spooler three times in the last two hours.',
      status: 'open',
      assignedTo: operatorUserObjectId,
      detailsBlobPath: blobPathBuilders.managementAlertDetails(demoContext.mspTenantId, 'alert_print_spooler'),
      createdAt: '2026-03-12T15:18:00.000Z',
      updatedAt: recentTimestamp,
    }),
    service.tables.managementAlerts.upsert({
      ...keyBuilders.entity.managementAlert(demoContext.mspTenantId, 'alert_mfa_drift', '2026-03-12T12:10:00.000Z'),
      id: 'alert_mfa_drift',
      mspTenantId: demoContext.mspTenantId,
      clientTenantId: northwindClientId,
      alertType: 'standards-drift',
      severity: 'high',
      sourceType: 'standard',
      sourceId: 'std_mfa_enforcement',
      title: 'MFA enforcement drift detected',
      summary: 'Two break-glass accounts are excluded from the current MFA policy assignment.',
      status: 'open',
      assignedTo: operatorUserObjectId,
      detailsBlobPath: blobPathBuilders.managementAlertDetails(demoContext.mspTenantId, 'alert_mfa_drift'),
      createdAt: '2026-03-12T12:10:00.000Z',
      updatedAt: recentTimestamp,
    }),
    service.tables.managementAlerts.upsert({
      ...keyBuilders.entity.managementAlert(demoContext.mspTenantId, 'alert_license_pool', '2026-03-12T09:40:00.000Z'),
      id: 'alert_license_pool',
      mspTenantId: demoContext.mspTenantId,
      clientTenantId: wingtipClientId,
      alertType: 'licensing',
      severity: 'low',
      sourceType: 'license',
      sourceId: 'sku_m365_e3',
      title: 'Only one spare E3 license remains',
      summary: 'Onboarding can proceed, but renewal planning should be scheduled this week.',
      status: 'open',
      detailsBlobPath: blobPathBuilders.managementAlertDetails(demoContext.mspTenantId, 'alert_license_pool'),
      createdAt: '2026-03-12T09:40:00.000Z',
      updatedAt: recentTimestamp,
    }),
    service.tables.managementSyncState.upsert({
      ...keyBuilders.entity.managementSyncState(demoContext.mspTenantId, northwindClientId, 'users'),
      mspTenantId: demoContext.mspTenantId,
      clientTenantId: northwindClientId,
      datasetName: 'users',
      lastSuccessfulSyncAt: recentTimestamp,
      lastAttemptedSyncAt: recentTimestamp,
      status: 'idle',
      recordCount: 27,
      updatedAt: recentTimestamp,
    }),
    service.tables.managementSyncState.upsert({
      ...keyBuilders.entity.managementSyncState(demoContext.mspTenantId, northwindClientId, 'standards'),
      mspTenantId: demoContext.mspTenantId,
      clientTenantId: northwindClientId,
      datasetName: 'standards',
      lastSuccessfulSyncAt: '2026-03-12T15:22:00.000Z',
      lastAttemptedSyncAt: '2026-03-12T15:22:00.000Z',
      status: 'idle',
      recordCount: 14,
      updatedAt: recentTimestamp,
    }),
    service.tables.managementSyncState.upsert({
      ...keyBuilders.entity.managementSyncState(demoContext.mspTenantId, wingtipClientId, 'users'),
      mspTenantId: demoContext.mspTenantId,
      clientTenantId: wingtipClientId,
      datasetName: 'users',
      lastSuccessfulSyncAt: '2026-03-12T15:16:00.000Z',
      lastAttemptedSyncAt: '2026-03-12T15:16:00.000Z',
      status: 'idle',
      recordCount: 54,
      updatedAt: recentTimestamp,
    }),
    service.tables.standardsResults.upsert({
      ...keyBuilders.entity.standardsResult(demoContext.mspTenantId, northwindClientId, 'std_mfa_enforcement'),
      mspTenantId: demoContext.mspTenantId,
      clientTenantId: northwindClientId,
      standardId: 'std_mfa_enforcement',
      status: 'non-compliant',
      severity: 'high',
      resultSummary: 'Break-glass accounts need documented exclusion policy review.',
      resultBlobPath: blobPathBuilders.standardResult(demoContext.mspTenantId, northwindClientId, 'std_mfa_enforcement'),
      lastEvaluatedAt: '2026-03-12T15:22:00.000Z',
      excluded: false,
    }),
    service.tables.standardsResults.upsert({
      ...keyBuilders.entity.standardsResult(demoContext.mspTenantId, wingtipClientId, 'std_secure_score'),
      mspTenantId: demoContext.mspTenantId,
      clientTenantId: wingtipClientId,
      standardId: 'std_secure_score',
      status: 'compliant',
      severity: 'medium',
      resultSummary: 'Tenant baseline score is above the target threshold.',
      resultBlobPath: blobPathBuilders.standardResult(demoContext.mspTenantId, wingtipClientId, 'std_secure_score'),
      lastEvaluatedAt: '2026-03-12T15:16:00.000Z',
      excluded: false,
    }),
    service.tables.workflows.upsert({
      ...keyBuilders.entity.workflow(demoContext.mspTenantId, ticketTriageWorkflowId),
      id: ticketTriageWorkflowId,
      mspTenantId: demoContext.mspTenantId,
      displayName: 'Ticket Triage Hub',
      description: 'Collect ticket, tenant, device, and documentation context into a guided technician run.',
      status: 'draft',
      draftBlobPath: blobPathBuilders.workflowDraft(demoContext.mspTenantId, ticketTriageWorkflowId),
      defaultClientTenantId: northwindClientId,
      triggerModeSummary: 'Manual from technician workspace',
      designAssistantMode: 'mixed',
      lastRunAt: '2026-03-12T15:05:00.000Z',
      lastRunStatus: 'succeeded',
      createdAt: demoTimestamp,
      createdBy: 'system:seed',
      updatedAt: recentTimestamp,
      updatedBy: 'system:seed',
    }),
    service.tables.workflows.upsert({
      ...keyBuilders.entity.workflow(demoContext.mspTenantId, onboardingWorkflowId),
      id: onboardingWorkflowId,
      mspTenantId: demoContext.mspTenantId,
      displayName: 'Guided User Onboarding',
      description: 'Prepare user, licensing, Teams policy, and documentation follow-up in one staged flow.',
      status: 'draft',
      draftBlobPath: blobPathBuilders.workflowDraft(demoContext.mspTenantId, onboardingWorkflowId),
      defaultClientTenantId: wingtipClientId,
      triggerModeSummary: 'Manual from tenant administration',
      designAssistantMode: 'ai-assisted',
      lastRunAt: '2026-03-11T16:43:00.000Z',
      lastRunStatus: 'succeeded',
      createdAt: demoTimestamp,
      createdBy: 'system:seed',
      updatedAt: recentTimestamp,
      updatedBy: 'system:seed',
    }),
    service.tables.workflows.upsert({
      ...keyBuilders.entity.workflow(demoContext.mspTenantId, driftWorkflowId),
      id: driftWorkflowId,
      mspTenantId: demoContext.mspTenantId,
      displayName: 'Standards Drift Review',
      description: 'Review standards findings, request approval, and launch guided remediation steps.',
      status: 'draft',
      draftBlobPath: blobPathBuilders.workflowDraft(demoContext.mspTenantId, driftWorkflowId),
      defaultClientTenantId: northwindClientId,
      triggerModeSummary: 'Manual or scheduled standards queue',
      designAssistantMode: 'manual',
      lastRunAt: '2026-03-12T14:41:00.000Z',
      lastRunStatus: 'partial',
      createdAt: demoTimestamp,
      createdBy: 'system:seed',
      updatedAt: recentTimestamp,
      updatedBy: 'system:seed',
    }),
  ]);

  await Promise.all([
    service.documents.workflowDrafts.put(
      buildTicketTriageWorkflow(ticketTriageWorkflowId),
      demoContext.mspTenantId,
      ticketTriageWorkflowId,
    ),
    service.documents.workflowDrafts.put(
      buildUserOnboardingWorkflow(onboardingWorkflowId),
      demoContext.mspTenantId,
      onboardingWorkflowId,
    ),
    service.documents.workflowDrafts.put(
      buildStandardsDriftWorkflow(driftWorkflowId),
      demoContext.mspTenantId,
      driftWorkflowId,
    ),
  ]);

  return service;
}

function buildTicketTriageWorkflow(workflowId: string): WorkflowDocument {
  return {
    schemaVersion: 1,
    workflowId,
    displayName: 'Ticket Triage Hub',
    trigger: {
      type: 'manual',
      config: {
        launchSurface: 'technician-workspace',
      },
    },
    nodes: [
      {
        id: 'trigger-start',
        type: 'trigger',
        label: 'Launch From Ticket',
        triggerType: 'manual',
        config: {
          contextSource: 'ticket',
        },
        position: { x: 48, y: 42 },
      },
      {
        id: 'load-ticket-context',
        type: 'connector-action',
        label: 'Load Ticket Context',
        connectorId: 'connector_psa',
        connectorVersionId: 'v1',
        actionId: 'getTicketContext',
        connectionId: 'conn_psa_primary',
        inputs: {
          includeTenant: true,
          includeDevice: true,
        },
        position: { x: 240, y: 42 },
      },
      {
        id: 'suggest-next-steps',
        type: 'ai-agent',
        label: 'Suggest Next Steps',
        agentId: 'agent_triage_guide',
        agentVersionId: 'v1',
        foundryProjectRef: 'foundry-default',
        operatingMode: 'suggest-only',
        inputTemplate: {
          includeDocumentation: true,
        },
        outputSchema: {
          recommendations: 'array',
          riskLevel: 'string',
        },
        approvalPolicy: {
          required: false,
        },
        timeoutSeconds: 45,
        maxRetries: 1,
        position: { x: 474, y: 42 },
      },
      {
        id: 'update-ticket-notes',
        type: 'connector-action',
        label: 'Update Ticket Notes',
        connectorId: 'connector_psa',
        connectorVersionId: 'v1',
        actionId: 'appendTicketNote',
        connectionId: 'conn_psa_primary',
        inputs: {
          noteSource: 'agent-summary',
        },
        position: { x: 706, y: 42 },
      },
    ],
    edges: [
      { id: 'edge-1', sourceNodeId: 'trigger-start', targetNodeId: 'load-ticket-context' },
      { id: 'edge-2', sourceNodeId: 'load-ticket-context', targetNodeId: 'suggest-next-steps' },
      { id: 'edge-3', sourceNodeId: 'suggest-next-steps', targetNodeId: 'update-ticket-notes' },
    ],
    variables: [
      {
        id: 'var_ticket_id',
        name: 'ticketId',
        type: 'string',
      },
    ],
    bindings: {
      connections: [
        {
          connectionId: 'conn_psa_primary',
          connectorId: 'connector_psa',
          alias: 'Primary PSA',
          scopeType: 'msp',
          requiredActions: ['getTicketContext', 'appendTicketNote'],
        },
      ],
    },
    ai: {
      draftSource: 'manual-or-ai',
      assumptions: ['Ticket is launched from technician workspace with tenant context attached.'],
    },
    editor: {
      viewport: {
        zoom: 0.88,
      },
    },
  };
}

function buildUserOnboardingWorkflow(workflowId: string): WorkflowDocument {
  return {
    schemaVersion: 1,
    workflowId,
    displayName: 'Guided User Onboarding',
    trigger: {
      type: 'manual',
      config: {
        launchSurface: 'tenant-admin',
      },
    },
    nodes: [
      {
        id: 'trigger-start',
        type: 'trigger',
        label: 'Launch From Tenant Admin',
        triggerType: 'manual',
        config: {
          contextSource: 'tenant',
        },
        position: { x: 48, y: 40 },
      },
      {
        id: 'create-user',
        type: 'connector-action',
        label: 'Create Entra User',
        connectorId: 'connector_graph',
        connectorVersionId: 'v1',
        actionId: 'createUser',
        connectionId: 'conn_graph_wingtip',
        inputs: {
          usageLocation: 'US',
        },
        position: { x: 258, y: 40 },
      },
      {
        id: 'assign-license',
        type: 'connector-action',
        label: 'Assign License',
        connectorId: 'connector_graph',
        connectorVersionId: 'v1',
        actionId: 'assignLicense',
        connectionId: 'conn_graph_wingtip',
        inputs: {
          sku: 'Microsoft 365 E3',
        },
        position: { x: 470, y: 40 },
      },
      {
        id: 'publish-doc-note',
        type: 'javascript',
        label: 'Add Checklist Note',
        inlineScript: 'return { checklist: "created" };',
        timeoutSeconds: 20,
        position: { x: 686, y: 40 },
      },
    ],
    edges: [
      { id: 'edge-1', sourceNodeId: 'trigger-start', targetNodeId: 'create-user' },
      { id: 'edge-2', sourceNodeId: 'create-user', targetNodeId: 'assign-license' },
      { id: 'edge-3', sourceNodeId: 'assign-license', targetNodeId: 'publish-doc-note' },
    ],
    variables: [],
    bindings: {
      connections: [
        {
          connectionId: 'conn_graph_wingtip',
          connectorId: 'connector_graph',
          alias: 'Wingtip Graph',
          scopeType: 'client',
          requiredActions: ['createUser', 'assignLicense'],
        },
      ],
    },
    ai: {
      draftSource: 'ai',
      assumptions: ['The tenant already has GDAP and the platform app registration in place.'],
    },
    editor: {
      viewport: {
        zoom: 0.92,
      },
    },
  };
}

function buildStandardsDriftWorkflow(workflowId: string): WorkflowDocument {
  return {
    schemaVersion: 1,
    workflowId,
    displayName: 'Standards Drift Review',
    trigger: {
      type: 'manual',
      config: {
        launchSurface: 'technician-workspace',
      },
    },
    nodes: [
      {
        id: 'trigger-start',
        type: 'trigger',
        label: 'Open Drift Review',
        triggerType: 'manual',
        config: {
          queue: 'standards',
        },
        position: { x: 44, y: 40 },
      },
      {
        id: 'load-drift-results',
        type: 'connector-action',
        label: 'Load Standards Result',
        connectorId: 'connector_graph',
        connectorVersionId: 'v1',
        actionId: 'getStandardsResult',
        connectionId: 'conn_graph_northwind',
        inputs: {
          standardId: 'std_mfa_enforcement',
        },
        position: { x: 270, y: 40 },
      },
      {
        id: 'needs-approval',
        type: 'condition',
        label: 'Needs Approval?',
        expression: 'result.severity === "high"',
        position: { x: 510, y: 40 },
      },
      {
        id: 'queue-remediation',
        type: 'connector-action',
        label: 'Queue Remediation Task',
        connectorId: 'connector_psa',
        connectorVersionId: 'v1',
        actionId: 'createTask',
        connectionId: 'conn_psa_primary',
        inputs: {
          board: 'Standards',
        },
        position: { x: 734, y: 40 },
      },
    ],
    edges: [
      { id: 'edge-1', sourceNodeId: 'trigger-start', targetNodeId: 'load-drift-results' },
      { id: 'edge-2', sourceNodeId: 'load-drift-results', targetNodeId: 'needs-approval' },
      {
        id: 'edge-3',
        sourceNodeId: 'needs-approval',
        targetNodeId: 'queue-remediation',
        conditionExpression: 'true',
      },
    ],
    variables: [],
    bindings: {
      connections: [
        {
          connectionId: 'conn_graph_northwind',
          connectorId: 'connector_graph',
          alias: 'Northwind Graph',
          scopeType: 'client',
          requiredActions: ['getStandardsResult'],
        },
        {
          connectionId: 'conn_psa_primary',
          connectorId: 'connector_psa',
          alias: 'Primary PSA',
          scopeType: 'msp',
          requiredActions: ['createTask'],
        },
      ],
    },
    ai: {
      draftSource: 'manual',
      assumptions: ['High-severity findings require technician review before changes are applied.'],
    },
    editor: {
      viewport: {
        zoom: 0.9,
      },
    },
  };
}
