import type { BlobPath, IsoUtcDateTime } from './common';
import type { BlobContainerName } from './storage';
declare function joinKeySegments(...segments: string[]): string;
declare function joinPathSegments(...segments: string[]): string;
declare function reverseTicks(value?: Date | string | number): string;
declare function padded(value: number, width: number): string;
declare function blobPath(container: BlobContainerName, ...segments: string[]): BlobPath;
export declare const keyBuilders: {
    partition: {
        msp: (mspTenantId: string) => string;
        mspClient: (mspTenantId: string, clientTenantId: string) => string;
        mspUser: (mspTenantId: string, userObjectId: string) => string;
        mspConnector: (mspTenantId: string, connectorId: string) => string;
        mspWorkflow: (mspTenantId: string, workflowId: string) => string;
        mspAgent: (mspTenantId: string, agentId: string) => string;
        execution: (executionId: string) => string;
        trigger: (mspTenantId: string, triggerId: string) => string;
        context: (mspTenantId: string, contextType: string, contextId: string) => string;
        standard: (mspTenantId: string, standardId: string) => string;
        tenantGroup: (mspTenantId: string, tenantGroupId: string) => string;
    };
    row: {
        profile: () => string;
        state: () => string;
        user: (userObjectId: string) => string;
        preference: (userObjectId: string) => string;
        inputProfile: (profileId: string) => string;
        client: (clientTenantId: string) => string;
        appRegistration: (appRegistrationId: string) => string;
        foundryProject: (environmentName: string) => string;
        managementProfile: (clientTenantId: string) => string;
        device: (deviceId: string) => string;
        ticket: (ticketId: string) => string;
        documentation: (documentationRecordId: string) => string;
        link: (linkedType: string, linkedId: string) => string;
        standard: (standardId: string) => string;
        assignment: (assignmentId: string) => string;
        sync: (datasetName: string) => string;
        connector: (connectorId: string) => string;
        version: (versionId: string) => string;
        action: (actionId: string) => string;
        agent: (agentId: string) => string;
        connection: (connectionId: string) => string;
        workflow: (workflowId: string) => string;
        trigger: (triggerId: string) => string;
        run: (executionId: string, at?: Date | string | number) => string;
        executionStep: (stepIndex: number, attempt: number) => string;
        aiRun: (aiAgentRunId: string, at?: Date | string | number) => string;
        alert: (alertId: string, at?: Date | string | number) => string;
        audit: (auditEventId: string, at?: Date | string | number) => string;
    };
    entity: {
        mspTenant: (mspTenantId: string) => TableEntityAddress;
        mspUser: (mspTenantId: string, userObjectId: string) => TableEntityAddress;
        userPreferences: (mspTenantId: string, userObjectId: string) => TableEntityAddress;
        userInputProfile: (mspTenantId: string, userObjectId: string, profileId: string) => TableEntityAddress;
        clientTenant: (mspTenantId: string, clientTenantId: string) => TableEntityAddress;
        clientAppRegistration: (mspTenantId: string, clientTenantId: string, appRegistrationId: string) => TableEntityAddress;
        foundryProject: (mspTenantId: string, environmentName: string) => TableEntityAddress;
        tenantManagementProfile: (mspTenantId: string, clientTenantId: string) => TableEntityAddress;
        managedUser: (mspTenantId: string, clientTenantId: string, managedUserId: string) => TableEntityAddress;
        ticket: (mspTenantId: string, ticketId: string) => TableEntityAddress;
        device: (mspTenantId: string, clientTenantId: string, deviceId: string) => TableEntityAddress;
        documentationRecord: (mspTenantId: string, clientTenantId: string, documentationRecordId: string) => TableEntityAddress;
        technicianContextLink: (mspTenantId: string, contextType: string, contextId: string, linkedType: string, linkedId: string) => TableEntityAddress;
        tenantGroup: (mspTenantId: string, tenantGroupId: string) => TableEntityAddress;
        tenantGroupMember: (mspTenantId: string, tenantGroupId: string, clientTenantId: string) => TableEntityAddress;
        standardsTemplate: (mspTenantId: string, standardId: string) => TableEntityAddress;
        standardsAssignment: (mspTenantId: string, standardId: string, assignmentId: string) => TableEntityAddress;
        standardsResult: (mspTenantId: string, clientTenantId: string, standardId: string) => TableEntityAddress;
        managementAlert: (mspTenantId: string, alertId: string, at?: Date | string | number) => TableEntityAddress;
        managementSyncState: (mspTenantId: string, clientTenantId: string, datasetName: string) => TableEntityAddress;
        connector: (mspTenantId: string, connectorId: string) => TableEntityAddress;
        connectorVersion: (mspTenantId: string, connectorId: string, connectorVersionId: string) => TableEntityAddress;
        connectorAction: (mspTenantId: string, connectorId: string, connectorVersionId: string, actionId: string) => TableEntityAddress;
        aiAgent: (mspTenantId: string, agentId: string) => TableEntityAddress;
        aiAgentVersion: (mspTenantId: string, agentId: string, agentVersionId: string) => TableEntityAddress;
        connection: (mspTenantId: string, connectionId: string, clientTenantId?: string) => TableEntityAddress;
        workflow: (mspTenantId: string, workflowId: string) => TableEntityAddress;
        workflowVersion: (mspTenantId: string, workflowId: string, workflowVersionId: string) => TableEntityAddress;
        workflowTrigger: (mspTenantId: string, workflowId: string, triggerId: string) => TableEntityAddress;
        pollingCheckpoint: (mspTenantId: string, triggerId: string) => TableEntityAddress;
        execution: (mspTenantId: string, workflowId: string, executionId: string, at?: Date | string | number) => TableEntityAddress;
        executionStep: (executionId: string, stepIndex: number, attempt: number) => TableEntityAddress;
        aiAgentRun: (mspTenantId: string, aiAgentRunId: string, at?: Date | string | number, workflowId?: string) => TableEntityAddress;
        auditEvent: (mspTenantId: string, auditEventId: string, at?: Date | string | number) => TableEntityAddress;
    };
};
export declare const blobPathBuilders: {
    connectorOpenApi: (mspTenantId: string, connectorId: string, connectorVersionId: string) => BlobPath;
    connectorSourceMetadata: (mspTenantId: string, connectorId: string, connectorVersionId: string) => BlobPath;
    connectorActions: (mspTenantId: string, connectorId: string, connectorVersionId: string) => BlobPath;
    connectorSchemas: (mspTenantId: string, connectorId: string, connectorVersionId: string) => BlobPath;
    connectorManifest: (mspTenantId: string, connectorId: string, connectorVersionId: string) => BlobPath;
    aiAgentInstructions: (mspTenantId: string, agentId: string, agentVersionId: string) => BlobPath;
    aiAgentTools: (mspTenantId: string, agentId: string, agentVersionId: string) => BlobPath;
    aiAgentEvaluationPolicy: (mspTenantId: string, agentId: string, agentVersionId: string) => BlobPath;
    aiAgentRunInput: (mspTenantId: string, agentId: string, aiAgentRunId: string) => BlobPath;
    aiAgentRunOutput: (mspTenantId: string, agentId: string, aiAgentRunId: string) => BlobPath;
    aiAgentRunTraceSummary: (mspTenantId: string, agentId: string, aiAgentRunId: string) => BlobPath;
    managementFullUserSync: (mspTenantId: string, clientTenantId: string, timestamp: IsoUtcDateTime | string) => BlobPath;
    managementOperationRequest: (mspTenantId: string, clientTenantId: string, operationId: string) => BlobPath;
    managementOperationResult: (mspTenantId: string, clientTenantId: string, operationId: string) => BlobPath;
    technicianTicketContext: (mspTenantId: string, ticketId: string) => BlobPath;
    technicianDeviceContext: (mspTenantId: string, clientTenantId: string, deviceId: string) => BlobPath;
    technicianDocumentationContext: (mspTenantId: string, clientTenantId: string, documentationRecordId: string) => BlobPath;
    standardDefinition: (mspTenantId: string, standardId: string) => BlobPath;
    standardResult: (mspTenantId: string, clientTenantId: string, standardId: string) => BlobPath;
    standardRemediation: (mspTenantId: string, clientTenantId: string, standardId: string) => BlobPath;
    managementAlertDetails: (mspTenantId: string, alertId: string) => BlobPath;
    workflowDraft: (mspTenantId: string, workflowId: string) => BlobPath;
    workflowDraftLayout: (mspTenantId: string, workflowId: string) => BlobPath;
    workflowVersionWorkflow: (mspTenantId: string, workflowId: string, workflowVersionId: string) => BlobPath;
    workflowVersionManifest: (mspTenantId: string, workflowId: string, workflowVersionId: string) => BlobPath;
    workflowVersionBindings: (mspTenantId: string, workflowId: string, workflowVersionId: string) => BlobPath;
    executionInput: (mspTenantId: string, workflowId: string, executionId: string) => BlobPath;
    executionOutput: (mspTenantId: string, workflowId: string, executionId: string) => BlobPath;
    executionLogs: (mspTenantId: string, workflowId: string, executionId: string) => BlobPath;
    executionState: (mspTenantId: string, workflowId: string, executionId: string) => BlobPath;
    executionStepInput: (mspTenantId: string, workflowId: string, executionId: string, stepIndex: number, attempt: number) => BlobPath;
    executionStepOutput: (mspTenantId: string, workflowId: string, executionId: string, stepIndex: number, attempt: number) => BlobPath;
    executionStepError: (mspTenantId: string, workflowId: string, executionId: string, stepIndex: number, attempt: number) => BlobPath;
    auditDetails: (mspTenantId: string, auditEventId: string) => BlobPath;
    tenantSettings: (mspTenantId: string) => BlobPath;
    clientNotes: (mspTenantId: string, clientTenantId: string) => BlobPath;
};
export declare const secretNameBuilders: {
    connection: (connectionId: string) => SecretReference;
    clientAppRegistration: (appRegistrationId: string) => SecretReference;
    webhook: (triggerId: string) => SecretReference;
};
export declare const storageNaming: {
    reverseTicks: typeof reverseTicks;
    blobPath: typeof blobPath;
    joinKeySegments: typeof joinKeySegments;
    joinPathSegments: typeof joinPathSegments;
    padded: typeof padded;
};
export {};
//# sourceMappingURL=keys.d.ts.map